package tel.schich.obd4s.obd

import java.nio.charset.StandardCharsets.US_ASCII
import java.util.concurrent.TimeUnit.{MINUTES, SECONDS}
import tel.schich.obd4s.obd.StandardMode.{ClearTroubleCodes, CurrentData, PendingTroubleCodes, PermanentTroubleCodes, ShowTroubleCodes, VehicleInfo}

import scala.collection.immutable.Map

abstract class PredefinedRequest[T, S <: Service](service: S, pid: Int, reader: Reader[T]) extends ParameterRequest(service, pid, reader)

enum CurrentDataRequest[T <: Response](pid: Int, reader: Reader[T]) extends PredefinedRequest(CurrentData, pid, reader) {
    case Support01To20                        extends CurrentDataRequest(0x00, PidSupportReader)
    case FuelSystemStatus                     extends CurrentDataRequest(0x03, FuelSystemStatusReader)
    case EngineLoad                           extends CurrentDataRequest(0x04, EngineLoadReader)
    case CoolantTemperature                   extends CurrentDataRequest(0x05, TemperatureReader)
    case ShortTermFuelTrim1                   extends CurrentDataRequest(0x06, FuelTrimReader)
    case LongTermFuelTrim1                    extends CurrentDataRequest(0x07, FuelTrimReader)
    case ShortTermFuelTrim2                   extends CurrentDataRequest(0x08, FuelTrimReader)
    case LongTermFuelTrim2                    extends CurrentDataRequest(0x09, FuelTrimReader)
    case FuelPressure                         extends CurrentDataRequest(0x0A, FuelPressureReader)
    case IntakeManifoldAbsolutePressure       extends CurrentDataRequest(0x0B, IntakeManifoldPressureReader)
    case EngineRpm                            extends CurrentDataRequest(0x0C, RpmReader)
    case VehicleSpeed                         extends CurrentDataRequest(0x0D, VehicleSpeedReader)
    case TimingAdvance                        extends CurrentDataRequest(0x0E, TimingAdvanceReader)
    case IntakeAirTemperature                 extends CurrentDataRequest(0x0F, TemperatureReader)
    case AirFlowRate                          extends CurrentDataRequest(0x10, AirFlowRateReader)
    case ThrottlePosition                     extends CurrentDataRequest(0x11, SingleBytePercentageReader)
    case OxygenSensorFuelVoltage1             extends CurrentDataRequest(0x14, OxygenSensorFuelVoltageReader)
    case OxygenSensorFuelVoltage2             extends CurrentDataRequest(0x15, OxygenSensorFuelVoltageReader)
    case OxygenSensorFuelVoltage3             extends CurrentDataRequest(0x16, OxygenSensorFuelVoltageReader)
    case OxygenSensorFuelVoltage4             extends CurrentDataRequest(0x17, OxygenSensorFuelVoltageReader)
    case OxygenSensorFuelVoltage5             extends CurrentDataRequest(0x18, OxygenSensorFuelVoltageReader)
    case OxygenSensorFuelVoltage6             extends CurrentDataRequest(0x19, OxygenSensorFuelVoltageReader)
    case OxygenSensorFuelVoltage7             extends CurrentDataRequest(0x1A, OxygenSensorFuelVoltageReader)
    case OxygenSensorFuelVoltage8             extends CurrentDataRequest(0x1B, OxygenSensorFuelVoltageReader)
    case EngineRuntime                        extends CurrentDataRequest(0x1F, RuntimeReader(SECONDS))
    case Support21To40                        extends CurrentDataRequest(0x20, PidSupportReader)
    case DistanceTraveledWithMilOn            extends CurrentDataRequest(0x21, DistanceReader(DistanceReader.KiloMeter))
    case FuelRailPressureRelativeToManifold   extends CurrentDataRequest(0x22, FuelRailPressureRelativeToManifoldReader)
    case FuelRailGaugePressure                extends CurrentDataRequest(0x23, FuelRailGaugePressureReader)
    case OxygenSensor1FuelAirVoltage1         extends CurrentDataRequest(0x24, OxygenSensorFuelAirVoltageReader)
    case OxygenSensor1FuelAirVoltage2         extends CurrentDataRequest(0x25, OxygenSensorFuelAirVoltageReader)
    case OxygenSensor1FuelAirVoltage3         extends CurrentDataRequest(0x26, OxygenSensorFuelAirVoltageReader)
    case OxygenSensor1FuelAirVoltage4         extends CurrentDataRequest(0x27, OxygenSensorFuelAirVoltageReader)
    case OxygenSensor1FuelAirVoltage5         extends CurrentDataRequest(0x28, OxygenSensorFuelAirVoltageReader)
    case OxygenSensor1FuelAirVoltage6         extends CurrentDataRequest(0x29, OxygenSensorFuelAirVoltageReader)
    case OxygenSensor1FuelAirVoltage7         extends CurrentDataRequest(0x2A, OxygenSensorFuelAirVoltageReader)
    case OxygenSensor1FuelAirVoltage8         extends CurrentDataRequest(0x2B, OxygenSensorFuelAirVoltageReader)
    case CommandedExhaustGasRecirculation     extends CurrentDataRequest(0x2C, SingleBytePercentageReader)
    case ExhaustGasRecirculationError         extends CurrentDataRequest(0x2D, SingleByteSignedPercentageReader)
    case CommandedEvaporativePurge            extends CurrentDataRequest(0x2E, SingleBytePercentageReader)
    case FuelTankLevelInput                   extends CurrentDataRequest(0x2F, SingleBytePercentageReader)
    case WarmupsSinceCodesCleared             extends CurrentDataRequest(0x30, CountReader)
    case DistanceTraveledSinceCodeClear       extends CurrentDataRequest(0x31, DistanceReader(DistanceReader.KiloMeter))
    case SystemVaporPressure                  extends CurrentDataRequest(0x32, SystemVaporPressureReader)
    case AbsoluteBarometricPressure           extends CurrentDataRequest(0x33, BarometricPressureReader)
    case OxygenSensor1FuelAirCurrent1         extends CurrentDataRequest(0x34, OxygenSensorFuelAirCurrentReader)
    case OxygenSensor1FuelAirCurrent2         extends CurrentDataRequest(0x35, OxygenSensorFuelAirCurrentReader)
    case OxygenSensor1FuelAirCurrent3         extends CurrentDataRequest(0x36, OxygenSensorFuelAirCurrentReader)
    case OxygenSensor1FuelAirCurrent4         extends CurrentDataRequest(0x37, OxygenSensorFuelAirCurrentReader)
    case OxygenSensor1FuelAirCurrent5         extends CurrentDataRequest(0x38, OxygenSensorFuelAirCurrentReader)
    case OxygenSensor1FuelAirCurrent6         extends CurrentDataRequest(0x39, OxygenSensorFuelAirCurrentReader)
    case OxygenSensor1FuelAirCurrent7         extends CurrentDataRequest(0x3A, OxygenSensorFuelAirCurrentReader)
    case OxygenSensor1FuelAirCurrent8         extends CurrentDataRequest(0x3B, OxygenSensorFuelAirCurrentReader)
    case CatalystTemperatureBank1             extends CurrentDataRequest(0x3C, CatalystTemperatureReader)
    case CatalystTemperatureBank2             extends CurrentDataRequest(0x3D, CatalystTemperatureReader)
    case CatalystTemperatureBank3             extends CurrentDataRequest(0x3E, CatalystTemperatureReader)
    case CatalystTemperatureBank4             extends CurrentDataRequest(0x3F, CatalystTemperatureReader)
    case Support41To60                        extends CurrentDataRequest(0x40, PidSupportReader)
    case ControlModuleVoltage                 extends CurrentDataRequest(0x42, ControlModuleVoltageReader)
    case AbsoluteLoadValue                    extends CurrentDataRequest(0x43, SingleBytePercentageReader)
    case FuelAirCommandedEquivalenceRatio     extends CurrentDataRequest(0x44, FuelAirEquivalenceRatioReader)
    case RelativeThrottlePosition             extends CurrentDataRequest(0x45, SingleBytePercentageReader)
    case AmbientAirTemperature                extends CurrentDataRequest(0x46, TemperatureReader)
    case AbsoluteThrottlePositionB            extends CurrentDataRequest(0x47, SingleBytePercentageReader)
    case AbsoluteThrottlePositionC            extends CurrentDataRequest(0x48, SingleBytePercentageReader)
    case AcceleratorPedalPositionD            extends CurrentDataRequest(0x49, SingleBytePercentageReader)
    case AcceleratorPedalPositionE            extends CurrentDataRequest(0x4A, SingleBytePercentageReader)
    case AcceleratorPedalPositionF            extends CurrentDataRequest(0x4B, SingleBytePercentageReader)
    case CommandedThrottleActuator            extends CurrentDataRequest(0x4C, SingleBytePercentageReader)
    case TimeRunWithMilOn                     extends CurrentDataRequest(0x4D, RuntimeReader(MINUTES))
    case TimeSinceTroubleCodesCleared         extends CurrentDataRequest(0x4E, RuntimeReader(MINUTES))
    case OxygenSensorMaxValues                extends CurrentDataRequest(0x4F, OxygenSensorMaxValuesReader)
    case MaximumAirFlowRate                   extends CurrentDataRequest(0x50, MaximumAirFlowRateReader)
    case FuelType                             extends CurrentDataRequest(0x51, FuelTypeReader)
    case EthanolFuelPercentage                extends CurrentDataRequest(0x52, SingleBytePercentageReader)
    case AbsoluteEvapSystemVaporPressure      extends CurrentDataRequest(0x53, AbsoluteEvapSystemVaporPressureReader)
    case EvapSystemVaporPressure              extends CurrentDataRequest(0x54, EvapSystemVaporPressureReader)
    case ShortTermSecondaryOxygenSensorTrim13 extends CurrentDataRequest(0x55, SecondaryOxygenSensorTrimReader)
    case LongTermSecondaryOxygenSensorTrim13  extends CurrentDataRequest(0x56, SecondaryOxygenSensorTrimReader)
    case ShortTermSecondaryOxygenSensorTrim24 extends CurrentDataRequest(0x57, SecondaryOxygenSensorTrimReader)
    case LongTermSecondaryOxygenSensorTrim24  extends CurrentDataRequest(0x58, SecondaryOxygenSensorTrimReader)
    case FuelRailAbsolutePressure             extends CurrentDataRequest(0x59, FuelRailPressureReader)
    case RelativeAcceleratorPedalPosition     extends CurrentDataRequest(0x5A, SingleBytePercentageReader)
    case HybridBatteryPackRemainingLife       extends CurrentDataRequest(0x5B, SingleBytePercentageReader)
    case EngineOilTemperature                 extends CurrentDataRequest(0x5C, TemperatureReader)
    case FuelInjectionTiming                  extends CurrentDataRequest(0x5D, FuelInjectionTimingReader)
    case EngineFuelRate                       extends CurrentDataRequest(0x5E, FuelRateReader)
    case Support61To80                        extends CurrentDataRequest(0x60, PidSupportReader)
    case DriverDemandTorque                   extends CurrentDataRequest(0x61, SingleBytePercentageReader)
    case ActualEngineTorque                   extends CurrentDataRequest(0x62, SingleBytePercentageReader)
    case EngineReferenceTorque                extends CurrentDataRequest(0x63, TorqueReader)
    case EngineTorqueData                     extends CurrentDataRequest(0x64, EngineTorqueDataReader)
    case Support81ToA0                        extends CurrentDataRequest(0x80, PidSupportReader)
    case SupportA1ToC0                        extends CurrentDataRequest(0xA0, PidSupportReader)
    case SupportC1ToE0                        extends CurrentDataRequest(0xC0, PidSupportReader)

    override val bytes: Array[Byte] = Array(pid.toByte)
}

object CurrentDataRequest {
    lazy val reverse: Map[Int, CurrentDataRequest[_ <: Response]]  = values.map(v => (v.pid, v)).toMap
}

case object ShowTroubleCodesRequest extends ServiceRequest(ShowTroubleCodes, DiagnosticTroubleCodeReader)
case object ClearTroubleCodeRequest extends ServiceRequest(ClearTroubleCodes, UnitReader)
case object PendingTroubleCodesRequest extends ServiceRequest(PendingTroubleCodes, DiagnosticTroubleCodeReader)

enum VehicleInfoRequest[T](pid: Int, reader: Reader[T]) extends PredefinedRequest(VehicleInfo, pid, reader) {
    case Support01To20         extends VehicleInfoRequest(0x00, PidSupportReader)
    case VehicleIdMessageCount extends VehicleInfoRequest(0x01, ByteReader)
    case VehicleId             extends VehicleInfoRequest(0x02, StringReader(US_ASCII))
    case EcuNameMessageCount   extends VehicleInfoRequest(0x09, ByteReader)
    case EcuName               extends VehicleInfoRequest(0x0A, StringReader(US_ASCII))

    override val bytes: Array[Byte] = Array(pid.toByte)
}

case object PermanentTroubleCodesRequest extends ServiceRequest(PermanentTroubleCodes, DiagnosticTroubleCodeReader)
